# Array Creation

In [2]:
import numpy as np

NumPy offers **six main ways** to create arrays. Which method you use depends on whether you’re starting with existing data, generating values, or loading from files.

---

### 1. Convert from Python structures
You can turn built-in Python containers like **lists** or **tuples** into NumPy arrays.

```python

In [5]:
import numpy as np

list_data = [1, 2, 3, 4]
tuple_data = (5, 6, 7, 8)

arr_from_list = np.array(list_data)
arr_from_tuple = np.array(tuple_data)

print(arr_from_list)   # [1 2 3 4]
print(arr_from_tuple)  # [5 6 7 8]

[1 2 3 4]
[5 6 7 8]


### 2. Use NumPy’s built-in functions

NumPy has many functions to quickly create arrays with specific patterns or default values.

In [3]:
print(np.arange(0, 10, 2))  # [0 2 4 6 8]
print(np.ones((2, 3)))      # 2x3 array of ones
print(np.zeros((3, 2)))     # 3x2 array of zeros
print(np.empty((2, 2)))     # 2x2 uninitialized array

[0 2 4 6 8]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]


### 3. Build from existing arrays

You can create new arrays by copying, reshaping, stacking, or modifying existing ones.

In [4]:
arr = np.array([1, 2, 3])
replicated = np.tile(arr, 3)         # Repeat array 3 times
reshaped = np.arange(6).reshape(2,3) # Reshape 1D → 2D

print(replicated)  # [1 2 3 1 2 3 1 2 3]
print(reshaped)    # [[0 1 2]
                   #  [3 4 5]]

[1 2 3 1 2 3 1 2 3]
[[0 1 2]
 [3 4 5]]


### 4. Load from files

Arrays can be loaded from disk in standard formats like .csv or NumPy’s .npy.

In [6]:
# Example: loading a CSV file
# arr = np.loadtxt("data.csv", delimiter=",")
# arr = np.genfromtxt("data.csv", delimiter=",")

# Example: saving and loading NumPy binary format
np.save("my_array.npy", arr_from_list)
loaded = np.load("my_array.npy")
print(loaded)

[1 2 3 4]
