In [2]:
import numpy as np


# Indexing on ndarrays in NumPy

NumPy arrays (`ndarrays`) can be indexed using the standard Python `x[obj]` syntax, where:
- `x` is the array
- `obj` is the selection (integer, slice, boolean mask, or another array)

There are three main types of indexing:
1. **Basic Indexing**
2. **Advanced Indexing (integer & boolean)**
3. **Field Access (for structured arrays)**

Indexing works for both **retrieving** and **assigning** data.

---

## Basic Indexing

### Single element indexing
Works like Python lists (0-based, supports negative indices).

In [6]:
import numpy as np

x = np.arange(10)
print("x:", x)

print("x[2] =", x[2])     # third element
print("x[-2] =", x[-2])   # second from last

# Reshape to 2D
x.shape = (2, 5)
print("\n2D x:\n", x)
print("x[1, 3] =", x[1, 3])
print("x[1, -1] =", x[1, -1])

x: [0 1 2 3 4 5 6 7 8 9]
x[2] = 2
x[-2] = 8

2D x:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
x[1, 3] = 8
x[1, -1] = 9


**Note -** If you provide fewer indices than dimensions, NumPy returns a **sub-array view**:

In [7]:
x = np.arange(10).reshape(2, 5)
print("x:\n", x)

row0 = x[0]
print("\nx[0] returns row0:", row0)
print("x[0][2] =", row0[2])
print("x[0, 2] =", x[0, 2])   # equivalent, but more efficient

x:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

x[0] returns row0: [0 1 2 3 4]
x[0][2] = 2
x[0, 2] = 2


In [5]:
# Boolean Mask
arr = np.array([1,2,3,4,5,6,7,8,9])
mask = arr % 2 == 0   # boolean mask: True where arr is even
print("Numbers % 2 are:", arr[mask])

Numbers % 2 are: [2 4 6 8]


## Slicing and Striding

NumPy slices work like Python’s `[start:stop:step]`, but extend to **N dimensions**.

**Important:** slicing returns a **view**, not a copy.

In [8]:
x = np.arange(10)
print("x:", x)

print("x[1:7:2] =", x[1:7:2])     # step 2
print("x[-2:10] =", x[-2:10])     # negative start
print("x[-3:3:-1] =", x[-3:3:-1]) # reverse
print("x[5:] =", x[5:])           # from index 5 to end

x: [0 1 2 3 4 5 6 7 8 9]
x[1:7:2] = [1 3 5]
x[-2:10] = [8 9]
x[-3:3:-1] = [7 6 5 4]
x[5:] = [5 6 7 8 9]


In [10]:
x = np.arange(24).reshape(4, 6)
print("x:\n", x)

print("\nRows 1 to 2, cols 2 to 4:\n", x[1:3, 2:5])
print("\nEvery other row:\n", x[::2])

x:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Rows 1 to 2, cols 2 to 4:
 [[ 8  9 10]
 [14 15 16]]

Every other row:
 [[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]


## Dimensional Indexing Tools

### `...` (Ellipsis)
Expands to the needed number of `:` to cover all dimensions.

In [18]:
x = np.arange(24).reshape(2, 3, 4)
print("x.shape:", x.shape)
print(x)

print("\nx[..., 0]:\n", x[..., 0])   # same as x[:, :, 0]

x.shape: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

x[..., 0]:
 [[ 0  4  8]
 [12 16 20]]


### `np.newaxis` (or `None`)
Used to expand dimensions.

In [17]:
x = np.arange(5)
print("x shape:", x.shape)
print("x:", x)

expanded = x[:, np.newaxis] + x[np.newaxis, :]
print("\nBroadcasted 2D addition:\n", expanded)

x shape: (5,)
x: [0 1 2 3 4]

Broadcasted 2D addition:
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


## Advanced Indexing

Triggered when `obj` is:
- an array of integers
- a boolean mask
- or a tuple containing them

Unlike slicing, advanced indexing **always returns a copy**.

### Integer array indexing

In [19]:
x = np.arange(10, 1, -1)
print("x:", x)

print("x[[3, 3, 1, 8]] =", x[[3, 3, 1, 8]])
print("x[[3, 3, -3, 8]] =", x[[3, 3, -3, 8]])

x: [10  9  8  7  6  5  4  3  2]
x[[3, 3, 1, 8]] = [7 7 9 2]
x[[3, 3, -3, 8]] = [7 7 4 2]


### Boolean indexing
Useful for filtering values.

In [20]:
x = np.array([1., -1., -2., 3])
print("Original x:", x)

x[x < 0] += 20
print("After adding 20 to negatives:", x)

Original x: [ 1. -1. -2.  3.]
After adding 20 to negatives: [ 1. 19. 18.  3.]


In [21]:
# Example: filtering rows by condition
x = np.arange(35).reshape(5, 7)
b = x > 20

print("Boolean mask:\n", b)
print("\nValues > 20:\n", x[b])

Boolean mask:
 [[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]

Values > 20:
 [21 22 23 24 25 26 27 28 29 30 31 32 33 34]


## Combining Indexing
You can mix slices, integer arrays, and boolean masks.

In [22]:
y = np.arange(35).reshape(5, 7)

# Rows 0,2,4 and columns 1:3
print(y[[0, 2, 4], 1:3])

# Equivalent to
print(y[:, 1:3][[0, 2, 4], :])

[[ 1  2]
 [15 16]
 [29 30]]
[[ 1  2]
 [15 16]
 [29 30]]


## Field Access (Structured Arrays)

In [23]:
x = np.zeros((2, 2), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])
print("x['a'] shape:", x['a'].shape, "dtype:", x['a'].dtype)
print("x['b'] shape:", x['b'].shape, "dtype:", x['b'].dtype)

x['a'] shape: (2, 2) dtype: int32
x['b'] shape: (2, 2, 3, 3) dtype: float64


## Flat Iterator Indexing

In [24]:
x = np.arange(6).reshape(2, 3)
print("x:\n", x)

print("x.flat[3] =", x.flat[3])        # single index
print("x.flat[[2, 4]] =", x.flat[[2, 4]])  # multiple

x:
 [[0 1 2]
 [3 4 5]]
x.flat[3] = 3
x.flat[[2, 4]] = [2 4]


## Assigning Values

In [25]:
x = np.arange(10)
x[2:7] = 1
print("x after slice assignment:", x)

x[2:7] = np.arange(5)
print("x after array assignment:", x)

# Type conversions
x = np.arange(5)
x[1] = 1.2   # truncated
print(x)

x after slice assignment: [0 1 1 1 1 1 1 7 8 9]
x after array assignment: [0 1 0 1 2 3 4 7 8 9]
[0 1 2 3 4]


## Dealing with Variable Indices
You can use tuples, `slice()` and `Ellipsis` programmatically.

In [27]:
z = np.arange(81).reshape(3, 3, 3, 3)
indices = (1, Ellipsis, 1)
print(z[indices])

[[28 31 34]
 [37 40 43]
 [46 49 52]]
